name: Build Docker

on:
  workflow_call:
    secrets:
      DOCKER_TOKEN:
        required: false # Only required for push
    inputs:
      platform:
        description: Platform to target
        required: true
        type: string
      runs-on:
        description: Runner to use
        required: true
        type: string
      push:
        description: Push images to registry
        required: false
        type: boolean
        default: false
    outputs:
      digest:
        description: Digest of built image
        value: ${{ jobs.docker-build.outputs.digest }}

permissions:
  contents: read
  packages: write

jobs:
  docker-build:
    outputs:
      digest: ${{ steps.docker_variant.outputs.digest }}
    runs-on: ${{ inputs.runs-on }}
    steps:
      - uses: actions/checkout@v5

      - name: Docker login DockerHub
        id: login_dockerhub
        if: ${{ inputs.push }}
        uses: docker/login-action@v3
        with:
          username: meshtastic
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Docker login GHCR
        id: login_ghcr
        if: ${{ inputs.push }}
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Sanitize platform string
        id: clean_plat
        # Replace preceding 'linux/' and slashes
        run: echo "arch=${{ inputs.platform }}" | sed 's|linux/||; s|/||g' >> $GITHUB_OUTPUT

      - name: Docker build and push
        uses: docker/build-push-action@v6
        id: docker_variant
        env:
          # Prefix for the image name on DockerHub
          prefix: |-
            ${{ ( (contains(inputs.platform, 'arm64') && '-arm64') || (contains(inputs.platform, 'arm/v7') && '-armv7') || (contains(inputs.platform, 'riscv64') && '-riscv64') ) || '' }}
        with:
          context: .
          file: Containerfile
          push: ${{ inputs.push }}
          platforms: ${{ inputs.platform }}
          tags: |
            docker.io/meshtastic/github-action-runner${{env.prefix}}:latest
            ghcr.io/${{ github.repository }}:${{ steps.clean_plat.outputs.arch }}
