name: Docker Image CI
on: workflow_dispatch

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Docker login
      run:  docker login -u meshtastic -p ${{secrets.DOCKER_TOKEN}}

    - name: Docker setup
      if: ${{ github.event_name != 'pull_request_target' && github.event_name != 'pull_request' }}
      uses: docker/setup-buildx-action@v2

    - name: Docker build and push
      if: ${{ github.ref == 'refs/heads/main' && github.event_name != 'pull_request_target' && github.event_name != 'pull_request' }}
      uses: docker/build-push-action@v5
      with:
        context: ./x64
        push: true
        tags: meshtastic/gh-runner:latest
