name: Docker Image CI
on:
  schedule:
    - cron: 0 8 1 * *
  workflow_dispatch: {}
  
jobs:

  build-x64:

    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v4

    - name: Docker login
      run:  docker login -u meshtastic -p ${{secrets.DOCKER_TOKEN}}

    - name: Docker setup
      uses: docker/setup-buildx-action@v3
      with:
        platforms: linux/amd64

    - name: Docker build and push
      uses: docker/build-push-action@v6
      with:
        platforms: linux/amd64
        context: ./x64
        push: true
        tags: meshtastic/github-action-runner:latest

  build-arm64:

    runs-on: ubuntu-24.04-arm

    steps:
    - uses: actions/checkout@v4
    - uses: docker/setup-qemu-action@v3
      name: Set up QEMU

    - name: Docker login
      run:  docker login -u meshtastic -p ${{secrets.DOCKER_TOKEN}}

    - name: Docker setup
      uses: docker/setup-buildx-action@v3
      with:
        platforms: linux/arm64

    - name: Docker build and push
      uses: docker/build-push-action@v6
      with:
        platforms: linux/arm64
        context: ./arm64
        push: true
        tags: meshtastic/github-action-runner-arm64:latest

  build-armhf:

    runs-on: ubuntu-24.04-arm

    steps:
    - uses: actions/checkout@v4
    - uses: docker/setup-qemu-action@v3
      name: Set up QEMU

    - name: Docker login
      run:  docker login -u meshtastic -p ${{secrets.DOCKER_TOKEN}}

    - name: Docker setup
      uses: docker/setup-buildx-action@v3
      with:
        platforms: linux/arm/v7

    - name: Docker build and push
      uses: docker/build-push-action@v6
      with:
        platforms: linux/arm/v7
        context: ./armhf
        push: true
        tags: meshtastic/github-action-runner-armv7:latest

  build-riscv64:

    # Will build with qemu
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v4
    - uses: docker/setup-qemu-action@v3
      name: Set up QEMU

    - name: Docker login
      run:  docker login -u meshtastic -p ${{secrets.DOCKER_TOKEN}}

    - name: Docker setup
      uses: docker/setup-buildx-action@v3
      with:
        platforms: linux/riscv64

    - name: Docker build and push
      uses: docker/build-push-action@v6
      with:
        platforms: linux/riscv64
        context: ./riscv64
        push: true
        tags: meshtastic/github-action-runner-riscv64:latest
