name: Docker Image CI
on: workflow_dispatch

jobs:

  build-x64:

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4

    - name: Docker login
      run:  docker login -u meshtastic -p ${{secrets.DOCKER_TOKEN}}

    - name: Docker setup
      uses: docker/setup-buildx-action@v3

    - name: Docker build and push
      uses: docker/build-push-action@v6
      with:
        context: ./x64
        push: true
        tags: meshtastic/github-action-runner:latest

  build-arm64:

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4
    - uses: docker/setup-qemu-action@v3
      name: Set up QEMU

    - name: Docker login
      run:  docker login -u meshtastic -p ${{secrets.DOCKER_TOKEN}}

    - name: Docker setup
      uses: docker/setup-buildx-action@v3
      with:
        platforms: linux/arm64

    - name: Docker build and push
      uses: docker/build-push-action@v6
      with:
        platforms: linux/arm64
        context: ./arm64
        push: true
        tags: meshtastic/github-action-runner:latest

  build-armhf:

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4
    - uses: docker/setup-qemu-action@v3
      name: Set up QEMU

    - name: Docker login
      run:  docker login -u meshtastic -p ${{secrets.DOCKER_TOKEN}}

    - name: Docker setup
      uses: docker/setup-buildx-action@v3
      with:
        platforms: linux/armv6

    - name: build raspios
      run: |
        cd armhf
        bash raspios.sh https://downloads.raspberrypi.com/raspios_lite_armhf/images/raspios_lite_armhf-2024-10-28/2024-10-22-raspios-bookworm-armhf-lite.img.xz bookworm lite 2024-10-22 armhf
        docker context use default

    - name: Docker build and push
      uses: docker/build-push-action@v6
      with:
        platforms: linux/armv6
        file: ./armhf/Dockerfile
        push: true
        tags: meshtastic/github-action-runner:latest
