name: Docker Image CI
on: workflow_dispatch

jobs:

  build:

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3

    - name: Docker login
      run:  docker login -u meshtastic -p ${{secrets.DOCKER_TOKEN}}

    - name: Docker setup
      uses: docker/setup-buildx-action@v2

    - name: Docker build and push
      uses: docker/build-push-action@v5
      with:
        context: ./x64
        push: true
        tags: meshtastic/github-action-runner:latest
